# Dakora Monorepo - Workspace Root

[tool.uv.workspace]
members = [
    "server",
    "packages/client-python",
    "cli",
]

[tool.uv]
dev-dependencies = [
    "build>=1.3.0",
    "twine>=6.2.0",
    "httpx>=0.25.0",
    "requests>=2.31.0",
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "tomli-w>=1.0.0",
    "azure-storage-blob>=12.19.0",
    "azure-identity>=1.15.0",
    "pytest-cov>=7.0.0",
]

[tool.black]
line-length = 88
target-version = ["py311"]
