[project]
name = "promptvault"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "bogdanpi", email = "bogdan@iduntechnologies.com" }
]
requires-python = ">=3.11"
dependencies = [
    "jinja2>=3.1.6",
    "pydantic>=2.11.9",
    "pyyaml>=6.0.2",
    "typer>=0.19.2",
    "watchdog>=6.0.0",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.urls]
Homepage = "https://github.com/bogdanpi/promptvault"
Repository = "https://github.com/bogdanpi/promptvault.git"
Issues = "https://github.com/bogdanpi/promptvault/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = []
