# Render Blueprint - Production deployment
services:
  # API Service
  - type: web
    name: dakora-api
    runtime: docker
    region: frankfurt
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    autoDeploy: false  # Manual deploy only
    # CRITICAL: Pre-deploy command runs database migrations before deploying new version
    # This ensures schema is always up-to-date and prevents breaking production
#    preDeployCommand: "cd /app && alembic upgrade head"
    envVars:
      - key: MODE
        value: production
      - key: DATABASE_URL
        sync: false  # Set in Render dashboard (Supabase connection string)
      - key: REDIS_URL
        sync: false  # Set in Render dashboard (Upstash URL) or leave empty if not needed

      # Azure Blob Storage (for prompt templates)
      - key: AZURE_STORAGE_CONTAINER
        sync: false  # Set in Render dashboard (e.g., "prompts")
      - key: AZURE_STORAGE_CONNECTION_STRING
        sync: false  # Set in Render dashboard (from Azure portal)
      # Alternative: Use AZURE_STORAGE_ACCOUNT_URL for managed identity (not needed if using connection string)

      # LLM API Keys
      - key: OPENAI_API_KEY
        sync: false  # Set in Render dashboard
      - key: ANTHROPIC_API_KEY
        sync: false  # Set in Render dashboard

      # Authentication (Clerk)
      - key: AUTH_REQUIRED
        value: "true"  # Set to "false" for no-auth mode
      - key: CLERK_JWT_ISSUER
        sync: false  # Set in Render dashboard (from Clerk dashboard)
      - key: CLERK_JWKS_URL
        sync: false  # Set in Render dashboard (from Clerk dashboard)
      - key: CLERK_WEBHOOK_SECRET
        sync: false  # Set in Render dashboard (from Clerk dashboard > Webhooks)
    healthCheckPath: /api/health
    plan: free

  # Studio Service
  - type: web
    name: dakora-studio
    runtime: docker
    region: frankfurt
    dockerfilePath: ./studio/Dockerfile
    dockerContext: ./studio
    autoDeploy: false  # Manual deploy only
    envVars:
      - key: VITE_API_URL
        sync: false  # Set to: https://dakora-api.onrender.com (after API is deployed)
      - key: VITE_AUTH_REQUIRED
        value: "true"  # Set to "false" for no-auth mode
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false  # Set in Render dashboard (from Clerk dashboard)
    healthCheckPath: /
    plan: free
