[project]
name = "dakora-client"
version = "1.0.0"
description = "Python SDK for Dakora AI Control Plane"
readme = "README.md"
authors = [
    { name = "bogdanpi", email = "bogdan@dakora.io" }
]
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.25.0",
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.optional-dependencies]
# Agent framework integrations (installs dakora-agents)
maf = ["dakora-agents[maf]~=1.0.0"]  # Must match major.minor version
agents = ["dakora-agents[all]~=1.0.0"]  # Must match major.minor version

[project.urls]
Homepage = "https://github.com/dakora-labs/dakora"
Repository = "https://github.com/dakora-labs/dakora.git"
Issues = "https://github.com/dakora-labs/dakora/issues"

[tool.uv.sources]
dakora-agents = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["dakora_client"]

[dependency-groups]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "respx>=0.20.0",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests_client"]
