name: Release CLI (dakora)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 2.0.0)'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version to release (e.g., 2.0.0)'
        required: true
        type: string

jobs:
  release-cli:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python 3.11
      run: uv python install 3.11

    - name: Update CLI version
      run: |
        cd cli
        # Install tomli-w for TOML writing
        uv pip install tomli-w
        uv run python -c "
        import tomllib
        import tomli_w

        with open('pyproject.toml', 'rb') as f:
            data = tomllib.load(f)

        data['project']['version'] = '${{ inputs.version }}'

        with open('pyproject.toml', 'wb') as f:
            tomli_w.dump(data, f)
        "

    - name: Install dependencies
      run: |
        cd cli
        uv sync

    - name: Run CLI tests
      run: |
        cd cli
        uv run pytest tests/ -v || echo "No CLI tests yet"

    - name: Build CLI package
      run: |
        cd cli
        uv build

    - name: Check package
      run: |
        cd cli
        uv run twine check dist/*

    - name: Smoke test CLI
      run: |
        python -m venv /tmp/test-cli
        /tmp/test-cli/bin/pip install cli/dist/*.whl
        /tmp/test-cli/bin/dakora --help
        echo "✅ CLI smoke test passed"

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        cd cli
        uv run twine upload dist/*

    - name: Create git tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add cli/pyproject.toml
        git commit -m "chore: bump CLI version to ${{ inputs.version }}"
        git tag -a "cli-v${{ inputs.version }}" -m "CLI Release v${{ inputs.version }}"
        git push origin main
        git push origin "cli-v${{ inputs.version }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: "cli-v${{ inputs.version }}"
        name: "CLI v${{ inputs.version }}"
        body: |
          ## Dakora CLI v${{ inputs.version }}

          Install with:
          ```bash
          pip install dakora==${{ inputs.version }}
          ```

          ### Usage
          ```bash
          dakora init
          dakora start
          ```
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}